version: '3.5'

services:

  frontend:
    image: ${FRONTEND_IMAGE}
    networks: [ mamis-network ]
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/

networks:
  mamis-network:
    external: true
    name: mamis-network
